blank_issues_enabled: false
contact_links:
  - name: Xelora Documentation
    url: https://github.com/Tencent/Xelora/blob/main/docs/QA.md
    about: Check Xelora FAQ
  - name: Discussions
    url: https://github.com/Tencent/Xelora/discussions
    about: Ask questions or share ideas in Discussions
